# Generated by Django 2.2.7 on 2019-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geri_Donusum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Geri_Donusum', models.CharField(max_length=200)),
            ],
        ),
    ]
