# Generated by Django 2.2.7 on 2019-12-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SahaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahaGuvenlik', models.CharField(max_length=200)),
            ],
        ),
    ]
